apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: he35ivd82-go 
  janus-idp.io/tekton: he35ivd82-go
  backstage.io/kubernetes-id: he35ivd82-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: he35ivd82-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml