apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: he35ivd82-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: he35ivd82-go 
  name: he35ivd82-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: he35ivd82-go 
